version: "3.8"

services:
  postgres:
    container_name: crud-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud-db
    ports: 
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
        
volumes:
  db:
